### ISSUE TITLE
openSUSE 42.2 - no write access in /var/pid

### ISSUE THREAD

**Issue by roseswe** [MegaV0lt/MV_Backup#1]
ralph:0:~/tmp/MV_Backup-master >  ./MV_Backup.sh -m ~/.local ~/tmp/tbackup
./MV_Backup.sh: line 314: /var/run/MV_Backup.pid: Permission denied
 FEHLER!  Die PID-Datei konnte nicht erzeugt werden!
ralphl:1:~/tmp/MV_Backup-master > uname -a
Linux dell 4.4.79-18.26-default #1 SMP Thu Aug 10 20:30:05 UTC 2017 (fa5a935) x86_64 x86_64 x86_64 GNU/Linux

If root is required you should add a check before.

**Comment by MegaV0lt** [comment]
On my Systems is ok without root. I will implement an check for the pid.

**Comment by MegaV0lt** [comment]
Please check the latest commit: 715567a04706efce4614a765e71960c06c08c846

Now the script only shows an warning instead of exiting.
