### ISSUE TITLE
Possible to change compression method(s)?

### ISSUE THREAD

**Issue by Uatschitchun** [MegaV0lt/MV_Backup#2]
Hi, nice tool you've done! Thx for that!

Two little questions, is it possible to change the compression method for log files and extra backups?

Somehow ark isn't able to open the compressed log file from my received mail, as it uses absolute paths which ark isn't able to open!? Thought it's because of .xz, s I changed it to .gz in the .sh to no avail, still absolute paths, which can't be opened... 
Could you help or enlighten me a little on that?

Second, I do not understand the **extra_maxinc** option, insbesondere im/den Zusammenhang mit **extra_maxbak**!?
```
# Anzahl der zusätzlichen Sicherungen, die behalten werden soll. 0 behält nur die aktuelle Version
#extra_maxbak[nr]=  # Vorgabe it 0

# Anzahl der inkrementellen Sicherungen. Wenn die Zahl erreicht ist, wird die Sicherung in ein
# Unterverzeichnis verschoben und eine neue Verion erstellt. Begrenzt durch extra_maxbak[nr]
#extra_maxinc[nr]=  # Vorgabe ist 7
```

**Comment by MegaV0lt** [comment]
The compression format of logs is set at line 921:
`  printf -v ARCH 'Logs_%(%F-%H%M)T.tar.xz' \
    || ARCH="Logs_$(date +'%F-%H%M').tar.xz"  # Archiv mit Datum und Zeit (kein :)`
You can change it here to .tar.gz for example:
`  printf -v ARCH 'Logs_%(%F-%H%M)T.tar.gz' \
    || ARCH="Logs_$(date +'%F-%H%M').tar.gz"  # Archiv mit Datum und Zeit (kein :)`

Tar has hard coded options in the script (line 930). For logfilecompression i use:
`    tar --create --absolute-names --auto-compress --file="$ARCHIV" "${LOGFILES[@]}" "${ERRLOGS[@]}"`
You can try to remove the --absolute-names or set an older tar format. For example:
`    tar --create --absolute-names --format=oldgnu --auto-compress --file="$ARCHIV" "${LOGFILES[@]}" "${ERRLOGS[@]}"`
From tar-help:

> Auswahl des Archiv-Formats:

  -H, --format=FORMAT        Archiv mit dem gegebenen Format anlegen

 FORMAT ist eines der folgenden:

    gnu                      GNU-tar-1.13.x-Format
    oldgnu                   GNU-Format wie mit tar <=1.12
    pax                      Format von POSIX 1003.1-2001 (pax)
    posix                    wie pax
    ustar                    Format von POSIX 1003.1-1988 (ustar)
    v7                       altes V7-tar-Format


So try one of oldgnu or v7. This maybe helps out. If not then try to remove the option --absolute-names

About the "extra*" Options. They are used to make a extra (2nd) copy of the backup using tar. If maxbac is set then only the actual tar is kept. If maxbak is 1 ore more there will be x old versions that  will be kept. The versions will be incremental. If the extra_maxinc is reached the backup is moved do a subfolder

I hope it helps. I am short in time. But please tell me if you have success

**Comment by Uatschitchun** [comment]
Thx!!

**Comment by MegaV0lt** [comment]
Option to choose the archiformat is added
https://github.com/MegaV0lt/MV_Backup/commit/c153f42a93abb55a189cb3cc6c9bce8be4392b0a
